application:
  app-title: Epic Pet Clinic
micronaut:
  application:
    name: epic-pet-clinic
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
